apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    team: finance
    version: 1.2.1
    environment: staging
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80