apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    team: finance
    version: 1.2.1
    environment: staging
spec:
  containers:
    - name: container-name
      image: image-name
      ports:
        - containerPort: 80